---
- name: Test Playbook
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars/main.yml"
  tasks:
    #Create Network for DNS server
    - os_network:
        state: present
        name: Infra_Network_A
        external: False

    - os_subnet:
        state: present
        network_name: Infra_Network_A
        name: Infra_Subnet_A-1
        cidr: 10.200.100.0/24
        dns_nameservers:
           - 8.8.8.8
           - 8.8.4.4
    #Create a router and associate it with an external 
    - os_router:
        state: present
        name: Standalone_Dns_Environment_Router
        network: public_network
        interfaces: 
           - Infra_Subnet_A-1
    #Create new Security Group for DNS
    - os_security_group:
        state: present
        name: DNS_Security_Group
        description: Security group for DNS Servers

    - os_security_group_rule:
        security_group: DNS_Security_Group
        protocol: tcp
        port_range_min: 53
        port_range_max: 53
        remote_ip_prefix: 0.0.0.0/0

    - os_security_group_rule:
        security_group: DNS_Security_Group
        protocol: udp
        port_range_min: 53
        port_range_max: 53
        remote_ip_prefix: 0.0.0.0/0


    #Create a UBUNTU VM
    - os_server:
        state: present
        name: DNS_Server
        image: a21363f4-2cb5-4d02-85e5-8c392bd61eef
        timeout: 200
        flavor: m1.large
        key_name: gsb-rbg-openstack-standard
        security_groups: default,DNS_Security_Group
        auto_floating_ip: yes
        nics:
           - net-name: Infra_Network_A
      register: dns_server_1

    - name: Add vm to inventory
      add_host:
        name: dnsserver1
        groups: dns_servers
        ansible_ssh_host: "{{ dns_server_1.server.public_v4 }}"
    - name: remove ip from known_hosts
      command: ssh-keygen -f /home/ubuntu/.ssh/known_hosts -R "{{ dns_server_1.server.public_v4 }}"


    - name: Wait to be sure ssh is available
      pause:
        seconds: 30

    - name: Install python on server
      raw: ssh -vvv -i ~/gsb-openstack1.pem ubuntu@{{ dns_server_1.server.public_v4 }} "sudo apt-get -y install python-minimal"
      register: ssh_out

    - name: Show output of the python setup
      debug:
        var: ssh_out
