---
- name: gather facts about a server
  hosts: localhost
  tasks:
    - name: Get facts about a server
      os_server_facts:
         server: DNS*
      register: serverinfo

    - shell: echo {{serverinfo}} | grep v4
      register: FloatingIP

    - debug:
        msg: "{{FloatingIP}}"
      
